use BookingBirthdayDb

INSERT INTO [User] (Name, Gender, DateOfBirth, Username, Password, Email, Phone, Address, Image_url, Role, Status) VALUES
('Admin', 'Nam', '2000-01-01', 'admin12345', '25d55ad283aa400af464c76d713c07ad', 'admin@gmail.com', '0123456789', 'abc', '/imgProfile/avatar.png', 'Admin', 'Active'),
('Guest', N'Nữ', '2000-01-01', 'guest12345', '25d55ad283aa400af464c76d713c07ad', 'example123@gmail.com', '9876543210', 'abc', '/imgProfile/avatar.png', 'Guest', 'Active'),
('Host', 'Nam', '2000-01-01', 'host12345', '25d55ad283aa400af464c76d713c07ad', 'demo5678@gmail.com', '1122334455', 'abc', '/imgProfile/avatar.png', 'Host', 'Active');

insert into [Categories] (name) values
('500k - 1tr'),
('1tr - 2tr'),
('2tr - 3tr'),
('3tr - 4tr'),
('4tr - 5tr'),
('> 5tr')

INSERT INTO [Package] (Name, Host_name, Price, Venue, Detail, Note, Status, UserId, category_id, image_url) VALUES
(N'Bữa Tiệc Sinh Nhật Thế Giới Động Vật Quận 1', 'Host', 1500000, N'123 Đường Nguyễn Huệ, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh', N'Trẻ em sẽ được khám phá thế giới động vật thông qua các trò chơi và hoạt động. Các trò chơi ngoài trời như cuộc đua ốc sên, cắm trại giả mạo và trò chơi tìm kiếm kho báu. Về thực đơn, Buffet đa dạng với các món ăn yêu thích của trẻ như bánh sandwich hình động vật, salad trái cây và bánh sinh nhật hình chú voi. Không gian được trang trí với hình ảnh động vật, bong bóng màu sắc và các vật dụng liên quan đến tự nhiên. Mỗi em nhỏ sẽ nhận được một túi quà tặng chứa đồ chơi động vật nhỏ, sách màu vẽ và nhãn dán với hình ảnh động vật.', N'Để hủy tiệc vui lòng thông báo cho chúng tôi trước ít nhất 3 ngày trước ngày diễn ra tiệc. Chúng tôi cam kết đảm bảo môi trường an toàn và vệ sinh cho bạn và con bạn. Để biết thêm thông tin, vui lòng liên hệ với chúng tôi qua số điện thoại hoặc email trong trang cá nhân. Đội ngũ hỗ trợ của chúng tôi luôn sẵn lòng giải đáp mọi thắc mắc và hỗ trợ bạn trong quá trình lựa chọn và tổ chức tiệc sinh nhật cho con yêu của bạn.', 'Active', 3, 2, '/imgPackage/tiec-1.jpg'),
(N'Bữa Tiệc Sinh Nhật Siêu Anh Hùng Quận 2', 'Host', 1000000, N'456 Đường Thảo Điền, Phường Thảo Điền, Quận 2, Thành phố Hồ Chí Minh', N'Trẻ em sẽ trở thành các siêu anh hùng và tham gia vào các cuộc phiêu lưu hấp dẫn. Trò chơi "Giải cứu thế giới", xây dựng trang phục siêu nhân và cuộc thi nhảy tung cánh. Pizza siêu nhân, nước ép trái cây và bánh kem hình biểu tượng các siêu anh hùng. Không gian được trang trí với biểu tượng các siêu anh hùng, bong bóng và phụ kiện liên quan. Mỗi em nhỏ sẽ nhận được một chiếc áo siêu nhân, mặt nạ và một sách truyện tranh về siêu anh hùng.', N'Để hủy tiệc vui lòng thông báo cho chúng tôi trước ít nhất 3 ngày trước ngày diễn ra tiệc. Chúng tôi cam kết đảm bảo môi trường an toàn và vệ sinh cho bạn và con bạn. Để biết thêm thông tin, vui lòng liên hệ với chúng tôi qua số điện thoại hoặc email trong trang cá nhân. Đội ngũ hỗ trợ của chúng tôi luôn sẵn lòng giải đáp mọi thắc mắc và hỗ trợ bạn trong quá trình lựa chọn và tổ chức tiệc sinh nhật cho con yêu của bạn.', 'Active', 3, 2, '/imgPackage/tiec-2.jpg'),
(N'Bữa Tiệc Sinh Nhật Lâu Đài Và Công Chúa Quận 3', 'Host', 2000000, N'789 Đường Nguyễn Văn Linh, Phường Phạm Ngũ Lão, Quận 3, Thành phố Hồ Chí Minh', N'Trẻ em sẽ được trải nghiệm cuộc sống của công chúa và hoàng tử trong một lâu đài cổ. Cuộc thi trang phục công chúa, làm vương miện và các trò chơi nhảy dây cổ điển. Sandwich kiểu lâu đài, nước trái cây pha chế và bánh kem hình lâu đài. Không gian được trang trí với hoa văn cổ điển, hình ảnh công chúa và lâu đài. Mỗi em nhỏ sẽ nhận được một chiếc vương miện, đồ chơi công chúa và một cuốn sách về câu chuyện cổ tích.', N'Để hủy tiệc vui lòng thông báo cho chúng tôi trước ít nhất 3 ngày trước ngày diễn ra tiệc. Chúng tôi cam kết đảm bảo môi trường an toàn và vệ sinh cho bạn và con bạn. Để biết thêm thông tin, vui lòng liên hệ với chúng tôi qua số điện thoại hoặc email trong trang cá nhân. Đội ngũ hỗ trợ của chúng tôi luôn sẵn lòng giải đáp mọi thắc mắc và hỗ trợ bạn trong quá trình lựa chọn và tổ chức tiệc sinh nhật cho con yêu của bạn.', 'Active', 3, 3, '/imgPackage/tiec-3.jpg'),
(N'Bữa Tiệc Sinh Nhật Phiêu Lưu Vàng Quận 4', 'Host', 2500000, N'234 Đường Tôn Thất Thuyết, Phường Tân Dinh, Quận 4, Thành phố Hồ Chí Minh', N'Trẻ em sẽ trở thành những nhà thám hiểm thực sự trong một cuộc phiêu lưu đầy mạo hiểm. Trò chơi "Tìm kho báu", xây dựng thuyền buồm nhỏ và cuộc đua thuyền trên hồ. Bánh mì sandwich gói túi, nước chanh và bánh kem hình bảo tàng. Không gian được trang trí với hình ảnh bản đồ, hòn đảo và các vật dụng liên quan đến cuộc phiêu lưu. Mỗi em nhỏ sẽ nhận được một chiếc kính lúp, một cặp binh nhìn xa và một bức tranh tô màu về cuộc phiêu lưu.', N'Để hủy tiệc vui lòng thông báo cho chúng tôi trước ít nhất 3 ngày trước ngày diễn ra tiệc. Chúng tôi cam kết đảm bảo môi trường an toàn và vệ sinh cho bạn và con bạn. Để biết thêm thông tin, vui lòng liên hệ với chúng tôi qua số điện thoại hoặc email trong trang cá nhân. Đội ngũ hỗ trợ của chúng tôi luôn sẵn lòng giải đáp mọi thắc mắc và hỗ trợ bạn trong quá trình lựa chọn và tổ chức tiệc sinh nhật cho con yêu của bạn.', 'Active', 3, 3, '/imgPackage/tiec-4.jpg'),
(N'Bữa Tiệc Sinh Nhật Âm Nhạc Và Rock n Roll Quận 5', 'Host', 3000000, N'567 Đường Nguyễn Trãi, Phường 1, Quận 5, Thành phố Hồ Chí Minh', N'Trẻ em sẽ trải nghiệm cuộc sống của các ngôi sao nhạc rock và tham gia vào một buổi hòa nhạc vui nhộn. Cuộc thi nhảy rock, học cách chơi nhạc cụ như guitar và trò chơi "Tìm kiếm ngôi sao rock". Sandwich thịt nướng, nước ngọt và bánh kem hình chiếc guitar. Không gian được trang trí với hình ảnh các ngôi sao nhạc rock, bóng bay và đèn sân khấu. Mỗi em nhỏ sẽ nhận được một chiếc guitar mini, một đĩa nhạc với các bài hát yêu thích và một bức tranh vẽ.', N'Để hủy tiệc vui lòng thông báo cho chúng tôi trước ít nhất 3 ngày trước ngày diễn ra tiệc. Chúng tôi cam kết đảm bảo môi trường an toàn và vệ sinh cho bạn và con bạn. Để biết thêm thông tin, vui lòng liên hệ với chúng tôi qua số điện thoại hoặc email trong trang cá nhân. Đội ngũ hỗ trợ của chúng tôi luôn sẵn lòng giải đáp mọi thắc mắc và hỗ trợ bạn trong quá trình lựa chọn và tổ chức tiệc sinh nhật cho con yêu của bạn.', 'Active', 3, 4, '/imgPackage/tiec-5.jpg')


