use BookingBirthdayDb

INSERT INTO [User] (Name, Gender, DateOfBirth, Username, Password, Email, Phone, Address, Image_url, Role, Status) VALUES
('Admin', 'Nam', '2000-01-01', 'admin12345', '25d55ad283aa400af464c76d713c07ad', 'admin@gmail.com', '0123456789', 'abc', '/imgProfile/avatar.png', 'Admin', 'Active'),
('Guest', N'Nữ', '2000-01-01', 'guest12345', '25d55ad283aa400af464c76d713c07ad', 'example123@gmail.com', '0987654321', 'abc', '/imgProfile/avatar.png', 'Guest', 'Active'),
('Host', 'Nam', '2000-01-01', 'host12345', '25d55ad283aa400af464c76d713c07ad', 'demo5678@gmail.com', '0122334455', 'abc', '/imgProfile/avatar.png', 'Host', 'Active');

INSERT INTO [Area] (Name) VALUES
(N'Quận 1'),
(N'Quận 2'),
(N'Quận 3'),
(N'Quận 4'),
(N'Quận 5'),
(N'Quận 6'),
(N'Quận 7'),
(N'Quận 8'),
(N'Quận 9'),
(N'Quận 10'),
(N'Quận 11'),
(N'Quận 12'),
(N'Quận Bình Tân'),
(N'Quận Bình Thạnh'),
(N'Quận Gò Vấp'),
(N'Quận Phú Nhuận'),
(N'Quận Tân Bình'),
(N'Quận Tân Phú'),
(N'Quận Thủ Đức')

INSERT INTO [Location] (Name, Address, AreaId, Status) VALUES
(N'Jollibee', N'503A Nguyễn Duy Trinh, phường Bình Trưng Đông, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'Jollibee', N'194D Pasteur, Phường 6, Quận 3, Thành phố Hồ Chí Minh', 3, 'Active'),
(N'Jollibee', N'204 Nguyễn Minh Khai, Phường 6, Quận 3, Thành phố Hồ Chí Minh', 3, 'Active'),
(N'Jollibee', N'875 Trần Hưng Đạo, Phường 1, Quận 5, Thành phố Hồ Chí Minh', 5, 'Active'),
(N'Jollibee', N'2354/356 Trần Hưng Đạo, Phường 2, Quận 5, Thành phố Hồ Chí Minh', 5, 'Active'),
(N'Jollibee', N'191 Quang Trung, Phường Hiệp Phú, Quận 9, Thành phố Hồ Chí Minh', 9, 'Active'),
(N'Jollibee', N'50 Lê Văn Việt, Phường Hiệp Phú, Quận 9, Thành phố Hồ Chí Minh', 9, 'Active'),
(N'Jollibee', N'11 Sư Vạn Hạnh, Quận 10, Thành phố Hồ Chí Minh', 10, 'Active'),
(N'Jollibee', N'497 Hòa Hảo, Phường 7, Quận 10, Thành phố Hồ Chí Minh', 10, 'Active'),
(N'Jollibee', N'30/3-30/3A Lê Văn Khương, Phường Thới An, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Jollibee', N'10A Tô Ký, Phường Trung Mỹ Tây, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Jollibee', N'B124-127 Nguyễn Văn Qúa, Phường Đông Hưng Thuận, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Jollibee', N'102 Phan Văn Hớn, Phường Tân Thới Nhất, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Jollibee', N'815 Hương Lộ 2, Phường Bình Trị Đông A, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'Jollibee', N'1231 Quốc lộ 1A, Khu Phố 5, Phường Bình Trị Đông B, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'Jollibee', N'688 Lê Đức Thọ, Phường 15, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'Jollibee', N'81 - 83 Phạm Văn Chiêu, Phường 14, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'Jollibee', N'12 Phan Văn Trị, Phường 7, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'Jollibee', N'48 Hoa Sứ, Phường 7, Quận Phú Nhuận, Thành phố Hồ Chí Minh', 16, 'Active'),
(N'Jollibee', N'15-17 Cộng Hòa, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Jollibee', N'360 Trường Chinh, Phường 13, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Jollibee', N'650  u Cơ, Phường 10, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Jollibee', N'131 Tân Hương, Phường Tân Quý, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'Jollibee', N'2 Trường Chinh, Phường Tây Thạnh, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'Jollibee', N'159 Hiệp Bình, Phường Hiệp Bình Chánh, Quận Thủ Đức, Thành phố Hồ Chí Minh', 19, 'Active'),
(N'Jollibee', N'102 Đặng Văn Bi, Phường Bình Thọ, Quận Thủ Đức, Thành phố Hồ Chí Minh', 19, 'Active'),
(N'Jollibee', N'240-242 Phạm Văn Đồng, Phường Hiệp Bình Chánh, Quận Thủ Đức, Thành phố Hồ Chí Minh', 19, 'Active'),
(N'Jollibee', N'68/1 Quốc lộ 13, Phường Hiệp Bình Chánh, Quận Thủ Đức, Thành phố Hồ Chí Minh', 19, 'Active'),
(N'KFC', N'78 Lê Lai, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh', 1, 'Active'),
(N'KFC', N'35 Trịnh Văn Cấn, Phường Cầu Ông Lãnh, Quận 1, Thành phố Hồ Chí Minh', 1, 'Active'),
(N'KFC', N'14 Phạm Ngọc Thạch, Phường 6, Quận 1, Thành phố Hồ Chí Minh', 1, 'Active'),
(N'KFC', N'2 Nguyễn Huy Tự, Phường Đa Kao, Quận 1, Thành phố Hồ Chí Minh', 1, 'Active'),
(N'KFC', N'88 Song Hành, Phường An Phú, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'KFC', N'195 Xô Viết Nghệ Tĩnh, Phường 17, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'KFC', N'72 Trần Não, Phường Bình An, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'KFC', N'456 Thảo Điền, Phường Thảo Điền, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'KFC', N'407C - 407D Lê Văn Sỹ, Phường 12, Quận 3, Thành phố Hồ Chí Minh', 3, 'Active'),
(N'KFC', N'14 Phạm Ngọc Thạch, Phường 6, Quận 3, Thành phố Hồ Chí Minh', 3, 'Active'),
(N'KFC', N'540 Cách Mạng Tháng 8, Phường 11, Quận 3, Thành phố Hồ Chí Minh', 3, 'Active'),
(N'KFC', N'213A Nguyễn Văn Cừ, Phường 3, Quận 5, Thành phố Hồ Chí Minh', 5, 'Active'),
(N'KFC', N'99 Ngô Quyền, Phường 11, Quận 5, Thành phố Hồ Chí Minh', 5, 'Active'),
(N'KFC', N'549 - 551 Hậu Giang, Phường 11, Quận 6, Thành phố Hồ Chí Minh', 6, 'Active'),
(N'KFC', N'95 Bà Hom, Phường 13, Quận 6, Thành phố Hồ Chí Minh', 6, 'Active'),
(N'KFC', N'78C - 78D Tân Hoà Đông, Phường 12, Quận 6, Thành phố Hồ Chí Minh', 6, 'Active'),
(N'KFC', N'101 Tôn Dật Tiên, Phường Tân Phú, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'KFC', N'719 Huỳnh Tấn Phát, Phường Phú Thuận, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'KFC', N'11 Bùi Bằng Đoàn, Phường Tân Phong, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'KFC', N'168 Lâm Văn Bền, Khu Phố 4, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'KFC', N'469 Nguyễn Hữu Thọ, Phường Tân Hưng, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'KFC', N'48 - 50 Cần Giuộc, Phường 13, Quận 8, Thành phố Hồ Chí Minh', 8, 'Active'),
(N'KFC', N'230  u Dương Lân, Phường 3, Quận 8, Thành phố Hồ Chí Minh', 8, 'Active'),
(N'KFC', N'193 Lê Văn Việt, Phường Hiệp Phú, Quận 9, Thành phố Hồ Chí Minh', 9, 'Active'),
(N'KFC', N'2 Đường Số 2, Phường Phước Bình, Quận 9, Thành phố Hồ Chí Minh', 9, 'Active'),
(N'KFC', N'1233 Nguyễn Duy Trinh, Phường Long Trường, Quận 9, Thành phố Hồ Chí Minh', 9, 'Active'),
(N'KFC', N'1 - 3 Ngô Gia Tự, Phường 2, Quận 10, Thành phố Hồ Chí Minh', 10, 'Active'),
(N'KFC', N'50 Lý Thái Tổ, Phường 9, Quận 10, Thành phố Hồ Chí Minh', 10, 'Active'),
(N'KFC', N'377 - 377 Minh Phụng, Phường 10, Quận 11, Thành phố Hồ Chí Minh', 11, 'Active'),
(N'KFC', N'265  u Cơ, Phường 5, Quận 11, Thành phố Hồ Chí Minh', 11, 'Active'),
(N'KFC', N'412 Nguyễn Văn Quá, Phường 4, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'KFC', N'167/2 Nguyễn Ảnh Thủ, Phường Trung Mỹ Tây, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'KFC', N'599 Hà Huy Giáp, Phường Thạnh Xuân, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'KFC', N'1 Đường 17A, Khu Phố 11, Phường Bình Trị Đông B, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'KFC', N'893B Tỉnh Lộ 10, Phường Bình Trị Đông B, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'KFC', N'756 Tân Kỳ Tân Quý, Phường Bình Hưng Hòa, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'KFC', N'195 Xô Viết Nghệ Tĩnh, Phường 17, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'KFC', N'170A Nơ Trang Long, Phường 12, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'KFC', N'217 Nguyễn Xí, Phường 13, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'FKC', N'366 Phan Văn Trị, Phường 5, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'FKC', N'84 Phạm Văn Chiêu, Phường 9, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'FKC', N'451 Thống Nhất, Phường 11, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'FKC', N'87 Thích Quảng Đức, Phường 4, Quận Phú Nhuận, Thành phố Hồ Chí Minh', 16, 'Active'),
(N'KFC', N'407C - 407D Lê Văn Sỹ, Phường 2, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'KFC', N'102 Phan Huy Ích, Phường 15, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'KFC', N'15/17 Cộng Hòa, Phường 4, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'KFC', N'466 Lý Thường Kiệt, Phường 7, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'KFC', N'111 Nguyễn Sơn, Phường Phú Thành, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'KFC', N'1 Vườn Lài, Phường Phú Thọ Hòa, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'KFC', N'1/1 Trường Chinh, Phường Tây Thành, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'KFC', N'76/78 Tân Sơn Nhì, Phường Tân Sơn Nhì, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'KFC', N'251 Võ Văn Ngân, Phường Linh Chiểu, Quận Thủ Đức, Thành phố Hồ Chí Minh', 19, 'Active'),
(N'KFC', N'672 Nguyễn Duy Trinh, Khu Phố 3, Quận Thủ Đức, Thành phố Hồ Chí Minh', 19, 'Active'),
(N'KFC', N'428 Nguyễn Văn Tăng, Phường Long Thạnh Mỹ, Quận Thủ Đức, Thành phố Hồ Chí Minh', 19, 'Active'),
(N'Lotteria', N'95A Trần Hưng Đạo, Phường Cầu Ông Lãnh, Quận 1, Thành phố Hồ Chí Minh', 1, 'Active'),
(N'Lotteria', N'330 Trần Hưng Đạo, Phường Nguyễn Cư Trinh, Quận 1, Thành phố Hồ Chí Minh', 1, 'Active'),
(N'Lotteria', N'11 Nguyễn Thị Minh Khai, Phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh', 1, 'Active'),
(N'Lotteria', N'2 Song Hành, Phường An Phú, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'Lotteria', N'Khu B, Khu Đô Thị Mới, Khu Đô Thị An Phú An Khánh, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'Lotteria', N'17 Mai Chí Thọ, Phường Bình Khánh, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'Lotteria', N'250B Lý Chính Thắng, Phường 9, Quận 3, Thành phố Hồ Chí Minh', 3, 'Active'),
(N'Lotteria', N'1 Nguyễn Thông, Phường 9, Quận 3, Thành phố Hồ Chí Minh', 3, 'Active'),
(N'Lotteria', N'102 Lê Quốc Hưng, Phường 12, Quận 4, Thành phố Hồ Chí Minh', 4, 'Active'),
(N'Lotteria', N'114 Trần Hưng Đạo, Phường 7, Quận 5, Thành phố Hồ Chí Minh', 5, 'Active'),
(N'Lotteria', N'66 Mạc Cửu/67 Vạn Kiếp, Phường 13, Quận 5, Thành phố Hồ Chí Minh', 5, 'Active'),
(N'Lotteria', N'801 Hồng Bàng, Phường 9, Quận 6, Thành phố Hồ Chí Minh', 6, 'Active'),
(N'Lotteria', N'211 - 213 Bình Phú, Phường 11, Quận 6, Thành phố Hồ Chí Minh', 6, 'Active'),
(N'Lotteria', N'52 Hậu Giang, Phường 6, Quận 6, Thành phố Hồ Chí Minh', 6, 'Active'),
(N'Lotteria', N'469 Nguyễn Hữu Thọ, Phường Tân Hưng, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'Lotteria', N'573 Huỳnh Tấn Phát, Phường Tân Thuận Đông, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'Lotteria', N'H4-2 Nguyễn Văn Linh/1397 Khu Phố Mỹ Khánh 2, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'Lotteria', N'1362 Huỳnh Tấn Phát, Phường Phú Mỹ, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'Lotteria', N'101 Tôn Dật Tiên, Khu Đô Thị Phú Mỹ Hưng, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'Lotteria', N'99 Nguyễn Thị Thập, Khu Dân Cư Cityland, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'Lotteria', N'111 Dương Bá Trạc, Phường 1, Quận 8, Thành phố Hồ Chí Minh', 8, 'Active'),
(N'Lotteria', N'54 Tuy Lý Vương, Phường 13, Quận 8, Thành phố Hồ Chí Minh', 8, 'Active'),
(N'Lotteria', N'68 Lê Văn Việt, Phường Hiệp Phú, Quận 9, Thành phố Hồ Chí Minh', 9, 'Active'),
(N'Lotteria', N'286 Đỗ Xuân Hợp, Phường Phước Long A, Quận 9, Thành phố Hồ Chí Minh', 9, 'Active'),
(N'Lotteria', N'572A 3 Tháng 2, Phường 14, Quận 10, Thành phố Hồ Chí Minh', 10, 'Active'),
(N'Lotteria', N'307A, Số Cũ/155A Đ. Tô Hiến Thành, Quận 10, Thành phố Hồ Chí Minh', 10, 'Active'),
(N'Lotteria', N'2 Ngô Gia Tự/145 Lý Thái Tổ, Phường 9, Quận 10, Thành phố Hồ Chí Minh', 10, 'Active'),
(N'Lotteria', N'11 Sư Vạn Hạnh, Phường 12, Quận 10, Thành phố Hồ Chí Minh', 10, 'Active'),
(N'Lotteria', N'968 3 Tháng 2, Phường 15, Quận 11, Thành phố Hồ Chí Minh', 11, 'Active'),
(N'Lotteria', N'184 Lê Đại Hành, Phường 15, Quận 11, Thành phố Hồ Chí Minh', 11, 'Active'),
(N'Lotteria', N'229 Nguyễn Thị Kiểu, Khu Phố 4, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Lotteria', N'4 Tô Ký, Phường Tân Chánh Hiệp, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Lotteria', N'159 - 160/1 Nguyễn Ảnh Thủ, Phường Trung Chánh, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Lotteria', N'311 Vành Đai Trong, Phường Bình Trị Đông B, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'Lotteria', N'1 Đường Số 17A, Phường Bình Trị Đông B, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'Lotteria', N'1271 Tỉnh Lộ 10, Phường Tân Tạo, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'Lotteria', N'445 Bạch Đằng, Phường 2, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'Lotteria', N'606 Điện Biên Phủ, Phường 22, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'Lotteria', N'292 Đinh Bộ Lĩnh, Phường 26, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'Lotteria', N'346B Lê Quang Định, Phường 11, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'Lotteria', N'6 Trần Trọng Kim, Khu Phố 5, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'Lotteria', N'72 Ngô Tất Tố, Phường 19, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'Lotteria', N'20A Điện Biên Phủ, Vinhomes Tân Cảng, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'Lotteria', N'242 Nguyễn Văn Lượng, Phường 10, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'Lotteria', N'647 Quang Trung, Phường 11, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'Lotteria', N'33 Nguyễn Văn Nghi, Phường 4, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'Lotteria', N'65 Phạm Văn Chiêu, Phường 14, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'Lotteria', N'1C5 Phan Xích Long, Phường 7, Phú Nhuận, Thành phố Hồ Chí Minh', 16, 'Active'),
(N'Lotteria', N'20 Cộng Hòa, Phường 12, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Lotteria', N'160 Lê Bình, Phường 4, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Lotteria', N'64-66 Bàu Cát, Phường 14, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Lotteria', N'187 Xuân Hồng, Phường 4, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Lotteria', N'60A Trường Sơn, Phường 2, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Lotteria', N'175 Độc Lập, Phường Tân Quý, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'Lotteria', N'380 Thoại Ngọc Hầu, Phường Phú Thạnh, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'Lotteria', N'175 Hòa Bình, Phường Hiệp Tân, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'Popeyes', N'58/13 Nguyễn Bỉnh Khiêm, Phường Đa Kao, Quận 1, Thành phố Hồ Chí Minh', 1, 'Active'),
(N'Popeyes', N'20 Thảo Điền, Khu Phố 2, Phường Thảo Điền, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'Popeyes', N'359 Nguyễn Duy Trinh, Khu Phố 6, Phường Bình Trưng Tây, Quận 2, Thành phố Hồ Chí Minh', 2, 'Active'),
(N'Popeyes', N'172 Khánh Hội, Phường 6, Quận 4, Thành phố Hồ Chí Minh', 4, 'Active'),
(N'Lotteria', N'326 An Dương Vương, Phường 4, Quận 5, Thành phố Hồ Chí Minh', 5, 'Active'),
(N'Popeyes', N'500B Nguyễn Văn Luông, Phường 12, Quận 6, Thành phố Hồ Chí Minh', 6, 'Active'),
(N'Popeyes', N'62 Nguyễn Đức Cảnh, Khu Phố Mỹ Khánh 3, Phường Tân Phong, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'Popeyes', N'1335 Huỳnh Tấn Phát, Phường Phú Thuận, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'Popeyes', N'519 Đường Nguyễn Thị Thập, Phường Tân Phong, Quận 7, Thành phố Hồ Chí Minh', 7, 'Active'),
(N'Popeyes', N'311 Tùng Thiện Vương, Phường 11, Quận 8, Thành phố Hồ Chí Minh', 8, 'Active'),
(N'Popeyes', N'222-228 Dương Bá Trạc, Phường 2, Quận 8, Thành phố Hồ Chí Minh', 8, 'Active'),
(N'Popeyes', N'411 Liên Tỉnh 5, Phường 5, Quận 8, Thành phố Hồ Chí Minh', 8, 'Active'),
(N'Popeyes', N'387 Đỗ Xuân Hợp, Phường Phước Long B, Quận 9, Thành phố Hồ Chí Minh', 9, 'Active'),
(N'Popeyes', N'372 Lê Văn Việt, Phường Tăng Nhơn Phú B, Quận 9, Thành phố Hồ Chí Minh', 9, 'Active'),
(N'Popeyes', N'397A Lê Đại Hành, Phường 11, Quận 11, Thành phố Hồ Chí Minh', 11, 'Active'),
(N'Popeyes', N'785 Nguyễn Văn Quá, Phường Đông Hưng Thuận, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Popeyes', N'143/6 Nguyễn Ảnh Thủ, Phường Trung Chánh, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Popeyes', N'117 Nguyễn Ảnh Thủ, Khu Phố 2, Phường Hiệp Thành, Quận 12, Thành phố Hồ Chí Minh', 12, 'Active'),
(N'Popeyes', N'223 Đường Số 7, Phường Bình Trị Đông B, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'Popeyes', N'756 Hương Lộ 2, Khu Phố 6, Phường Bình Trị Đông A, Quận Bình Tân, Thành phố Hồ Chí Minh', 13, 'Active'),
(N'Popeyes', N'171 Nguyễn Xí, Phường 26, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'Popeyes', N'67-69 D2, Phường 25, Quận Bình Thạnh, Thành phố Hồ Chí Minh', 14, 'Active'),
(N'Popeyes', N'121 Lê Đức Thọ, Phường 17, Quận Gò Vấp, Thành phố Hồ Chí Minh', 15, 'Active'),
(N'Popeyes', N'405 Thống Nhất, Phường 11, Quận Gò Vấp Thành phố Hồ Chí Minh', 15, 'Active'),
(N'Popeyes', N'15 – 17 Cộng Hòa, Phường 4, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Popeyes', N'28 Phan Huy Ích, Phường 15, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Popeyes', N'75 Đồng Đen, Phường 12, Quận Tân Bình, Thành phố Hồ Chí Minh', 17, 'Active'),
(N'Popeyes', N'68 CN1, Phường Sơn Kỳ, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'Popeyes', N'33 Gò Dầu, Phường Tân Sơn Nhì, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'Popeyes', N'661/1 - 661/3 Lũy Bán Bích, Phường Phú Thạnh, Quận Tân Phú, Thành phố Hồ Chí Minh', 18, 'Active'),
(N'Popeyes', N'89 Hiệp Bình, Phường Hiệp Bình Chánh, Quận Thủ Đức, Thành phố Hồ Chí Minh', 19, 'Active'),
(N'Popeyes', N'303 Võ Văn Ngân, Phường Linh Chiểu, Quận Thủ Đức, Thành phố Hồ Chí Minh', 19, 'Active')

INSERT INTO Theme ([Name] ,[UserId] ,[Status]) Values
(N'Pikachu',3,N'Active'),
(N'Doraemon',3,N'Active'),
(N'Hello Kitty',3,N'Active'),
(N'Chuột Minnie',3,N'Active'),
(N'Công Chúa',3,N'Active'),
(N'Frozen',3,N'Active'),
(N'Tiên Cá',3,N'Active'),
(N'Kỳ Lân',3,N'Active'),
(N'Cup Head',3,N'Active'),
(N'Minion',3,N'Active'),
(N'Minecraft',3,N'Active'),
(N'Roblox',3,N'Active'),
(N'Avengers',3,N'Active'),
(N'Khủng Long',3,N'Active'),
(N'Superman',3,N'Active'),
(N'Spiderman',3,N'Active'),
(N'Phù Thủy',3,N'Active'),
(N'Liên Hệ',3,N'Active')


